# **Multiplicación de matrices**

In [1]:
import numpy as np

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

resultado = np.dot(A, B)
print("Resultado de la multiplicación de matrices:")
print(resultado)

Resultado de la multiplicación de matrices:
[[0.98003335 0.70356552 1.40084179]
 [0.64763675 0.27878043 1.01688051]
 [1.44132745 0.97412856 1.79283859]]


# **Vectorización de operaciones**


In [2]:
arr = np.array([1, 2, 3, 4, 5])

suma_total = np.sum(arr)
print("Suma total de los elementos del array:", suma_total)


Suma total de los elementos del array: 15


# **Broadcasting**

In [3]:
arr = np.array([1, 2, 3, 4, 5])

resultado = arr + 2
print("Resultado de la suma con broadcasting:")
print(resultado)

Resultado de la suma con broadcasting:
[3 4 5 6 7]


In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
result = a + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([10, 20, 30])

result = a * b

print(result)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([10, 20, 30])

result = a + b

print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


# **Indexación y segmentación avanzadas**

In [11]:
arr = np.array([1, 2, 3, 4, 5])

resultado = arr[arr > 2]
print("Elementos mayores que 2:", resultado)

Elementos mayores que 2: [3 4 5]


In [10]:
matriz_tridimensional = np.array([[[1, 2, 3],
                                   [4, 5, 6],
                                   [7, 8, 9]],

                                  [[10, 11, 12],
                                   [13, 14, 15],
                                   [16, 17, 18]],

                                  [[19, 20, 21],
                                   [22, 23, 24],
                                   [25, 26, 27]]])

elemento = matriz_tridimensional[1, 2, 0]
print("Elemento en la posición (1, 2, 0):", elemento)

submatriz = matriz_tridimensional[:, 1:, :]
print("\nSubmatriz:\n", submatriz)


Elemento en la posición (1, 2, 0): 16

Submatriz:
 [[[ 4  5  6]
  [ 7  8  9]]

 [[13 14 15]
  [16 17 18]]

 [[22 23 24]
  [25 26 27]]]


# **Herramientas para álgebra lineal y estadísticas**

In [9]:
arr = np.array([1, 2, 3, 4, 5])

media = np.mean(arr)
desviacion_estandar = np.std(arr)
print("Media del array:", media)
print("Desviación estándar del array:", desviacion_estandar)

Media del array: 3.0
Desviación estándar del array: 1.4142135623730951
